### ISSUE TITLE
Incompatibility with lodash 4.17.4

### ISSUE THREAD

**Issue by droganov** [azazdeaz/match-media-mock#1]
MatchMediaMock.js refers to non-existing lodash path 'lodash/lang/clone'

```
ERROR in ./~/match-media-mock/lib/MatchMediaMock.js
... | Module not found: Error: Can't resolve 'lodash/lang/clone'
```

Please update MatchMediaMock.js or include a dependancy to package.json

**Comment by azazdeaz** [comment]
It's in the package.json https://github.com/azazdeaz/match-media-mock/blob/master/package.json#L30
Maybe reinstalling the node_modules could help.
