### ISSUE TITLE
MatchMediaQueryList should also return a media key

### ISSUE THREAD

**Issue by jesse-mm** [azazdeaz/match-media-mock#2]
First of all thank you for supplying this NPM module! When using the module I found out the MediaQueryList object isn't returning the media key as [expected.](https://drafts.csswg.org/cssom-view/#the-mediaquerylist-interface) It would be great if you could fix this issue.

Thanks!

**Comment by PaulBunkerWhich** [comment]
This does not seem to be in the version currently published to NPM

![screen shot 2018-07-09 at 11 45 05](https://user-images.githubusercontent.com/28861630/42446282-99af6bc0-836d-11e8-9016-78a3ba0a45e0.png)
